name: "Show Secrets"
on: push
jobs:
  show-secrets:
    name: "Show secrets"
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SECRETS: ${{ toJson(secrets) }}
        run: echo $SECRETS
